[package]
name = "rocolatey-lib"
version = "0.5.4"
authors = ["Manfred Wallner <schusterfredl@mwallner.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.22.0"
glob = "0.3.0"
futures = "0.3.14"
reqwest = "0.11.3"
indicatif = "0.15.0"
semver = "0.11.0"
regex = "1.5.4"
walkdir = "2.3.2"
http-auth-basic = "0.1.3"
